# Generated by Django 6.0.7 on 2026-07-08 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Song",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("leader", models.CharField(max_length=100)),
                ("music_key", models.CharField(max_length=50)),
                (
                    "category",
                    models.CharField(
                        choices=[("Worship", "Worship"), ("Praise", "Praise")],
                        default="Worship",
                        max_length=20,
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Music",
        ),
        migrations.RenameField(
            model_name="contactmessage",
            old_name="created",
            new_name="submitted_at",
        ),
        migrations.AddField(
            model_name="event",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="events/"),
        ),
    ]
