# Generated by Django 6.0.7 on 2026-07-08 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0002_song_delete_music_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="announcement",
            options={"ordering": ["-submitted_at"]},
        ),
        migrations.RenameField(
            model_name="announcement",
            old_name="created",
            new_name="submitted_at",
        ),
    ]
