# Generated by Django 6.0.7 on 2026-07-08 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0003_alter_announcement_options_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="announcement",
            old_name="message",
            new_name="messages",
        ),
    ]
