# Generated by Django 6.0.7 on 2026-07-08 22:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0004_rename_message_announcement_messages"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="gallery",
            options={"ordering": ["-uploaded_at"]},
        ),
        migrations.AddField(
            model_name="gallery",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="gallery",
            name="media_file",
            field=models.FileField(
                blank=True,
                help_text="Upload video, audio, or other media files",
                null=True,
                upload_to="gallery/media/",
            ),
        ),
        migrations.AddField(
            model_name="gallery",
            name="uploaded_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="gallery",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="gallery/"),
        ),
    ]
