# Generated by Django 6.0.7 on 2026-07-08 22:49

import mainapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0005_alter_gallery_options_gallery_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="events/",
                validators=[mainapp.models.validate_file_size],
            ),
        ),
        migrations.AlterField(
            model_name="gallery",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="gallery/",
                validators=[mainapp.models.validate_file_size],
            ),
        ),
        migrations.AlterField(
            model_name="gallery",
            name="media_file",
            field=models.FileField(
                blank=True,
                help_text="Upload video, audio, or other media files (Max: 100MB)",
                null=True,
                upload_to="gallery/media/",
                validators=[mainapp.models.validate_file_size],
            ),
        ),
    ]
